### ISSUE TITLE
Add support for -S[<keyid>], --gpg-sign[=<keyid>] for 'git commit'

### ISSUE THREAD

**Issue by jlec** [peritus/bumpversion#109] opened 2015-08-07 09:49 UTC
Would be nice to have things signed.

**Comment by peritus** [comment] 2015-08-07 10:35
Duplicate of #2 and thus a priority. Keeping this open.

**Comment by peritus** [comment] 2015-11-10 11:17
Please follow ticket #74 for progress on this.

**Closed by peritus** 2015-11-10 11:17 UTC
