### ISSUE TITLE
All strings matching current version are bumping up in setup.py file.

### ISSUE THREAD

**Issue by mss30** [peritus/bumpversion#201] opened 2019-04-18 12:01 UTC
Here is the problem. My `setup.py` look like this (as below):

```python
from setuptools import setup, find_packages

setup(
    name='my-pack',
    version='0.2.1',
    packages=find_packages(exclude=["*.tests", "*.tests.*", "tests.*", "tests"]),
    install_requires=[
        'someotherpackage==0.2.1',
    ],
)
```

After running bumpvesrion command ```bumpversion --current-version `python setup.py --version` patch setup.py>``` I got this output:

```python
from setuptools import setup, find_packages

setup(
    name='my-pack',
    version='0.2.2',
    packages=find_packages(exclude=["*.tests", "*.tests.*", "tests.*", "tests"]),
    install_requires=[
        'someotherpackage==0.2.2',
    ],
)
```

The problem is the bumpversion should only bump the version of `my-pack` only instead it is bumping all the versions (or I can say strings) matching current version.

Is there any available solution for this issue?

**Comment by peritus** [comment] 2019-04-18 12:15
Hey. Please have a look at the `search` and `replace` options.

Closing as duplicate of #178 #76 #46, but feel free to re-open.

**Closed by peritus** 2019-04-18 12:15 UTC

**Comment by mss30** [comment] 2019-04-18 12:35
Thanks for replying. I'd tried to add `search` and `replace` options but these don't work as expected.

Here is my `.bumpversion.cfg` file:
[bumpversion]
current_version = 0.2.2
```
[bumpversion:file:setup.py]
search = version='{current_version}',
replace = version='{new_version}',
```

And here is the `setup.py` when I run the bumpversion command:

```python
from setuptools import setup, find_packages

setup(
    name='my-pack',
    version='0.2.3',
    packages=find_packages(exclude=["*.tests", "*.tests.*", "tests.*", "tests"]),
    install_requires=[
        'someotherpackage==version='0.2.3',',
    ],
)
``` 

It would be great if you can help me in this problem.
